---
title: "Notes: The Unix Workbench"
author: "Adam Austin"
output: html_document
---

## Chapter 4

### Getting help

Help for a known command

`man command_name`

Searching for command names and inside docs

`apropos search_term`

### Regular expressions

Search a file

`grep "expression" filename.ext`

Extended regular expressions

`egrep "expression" filename.txt`

Same as `grep -E ...` and for GNU `grep`, same as plain ol' `grep` according to the docs on my RHEL.

Fixed regular expressions

`fgrep "expression" filename.txt`

Capturing groups let you search for whole groups at a time, e.g.

`egrep "(iss){2}" states.txt`

searches for 2 instances of "iss" in a single state's names (matches Mississippi).

Arbitrary sets are defined in square brackets, _e.g._ `[0-9]` or `[abc]`.

Anchors are `^` for start and `$` for end.  ("First you get the power, then you get the money.")

You display line numbers with `-n` flag.  You search recursively with `-r`.

#### Metacharacter reference table


| Metacharacter |               Meaning                |
|--------------:|:-------------------------------------|
|       .       |            Any Character             |
|      \\w      |                A Word                |
|      \\W      |              Not a Word              |
|      \\d      |               A Digit                |
|      \\D      |             Not a Digit              |
|      \\s      |              Whitespace              |
|      \\S      |            Not Whitespace            |
|     [abcd]     |         A Set of Characters          |
|    [^abcd]     |           Negation of Set            |
|     [e-q]     |        A Range of Characters         |
|       ^       |         Beginning of String          |
|       $       |            End of String             |
|      \\n      |               Newline                |
|       +       |       One or More of Previous        |
|       *       |       Zero or More of Previous       |
|       ?       |       Zero or One of Previous        |
|    &#124;     | Either the Previous or the Following |
|      {6}      |        Exactly 6 of Previous         |
|    {4, 6}     |     Between 4 and 6 of Previous      |
|     {4, }     |        4 or more of Previous         |


#### Finding by file name matching

`find . -name "filename"`

#### Bash history

The file `~/.bash_history` contains command history.  You can `grep` it!

### File differences

#### Displaying diffs

`diff` and `sdiff` (side-by-side) show file differences.

#### File hashes

You can build an `md5` hash of a file with `md5 filename`.  Two identical files should have the same hash.

And `sha-1` hash is built similarly: `shasum filename`.

### Piping

Send `stdout` from one command as `stdin` to another.  Use it in creative ways, _e.g._ to show the files in a directory that match a pattern with `ls -al | grep "pattern" | less`.

### Make

`make` is a program that that, in early computing, tried to solve the problem of how software should be shared and installed across machines.  The philosophy of `make` is that, to install new software, you download all files for installation to a directory, `cd` to that location, and run `make` to take care of everything else.

A `makefile` specifies the relationship between various files and programs.  `makefile`s illustrate rules.  One such rule:


```
[target]: [dependencies...]
  [commands...]
```

Note these must be tab-indented!  To make the target, you run `make target` and the commands under that target are executed.  Making the same target, if nothing needs to be updated, will result in a message telling you that everything is current.  If a dependency gets updated, then running `make` again will update the target.  Here's how to use a dependency:

```
readme.txt: toc.txt
  echo "This journal contains the following number of entries:" > readme.txt
  wc -l toc.txt | egrep -o "[0-9]+" >> readme.txt
```

Now when `toc.txt` is updated, `make readme.txt` can be rerun to generate the file again.

Using an `all` statement at the top of the `makefile` allows us to simply run `make` to build all files.

`all: file1 file2 file3`

Using a `clean` statement at the end of the `makefile` tells `make` how to clean up at the end.

```
clean:
  rm file1
  rm file2
```

Other resources:
[Karl Broman](https://twitter.com/kwbroman)'s
[tutorial](http://kbroman.org/minimal_make/) or 
[Chase Lambert](http://chaselambda.com)'s
[makefiletutorial.com](http://makefiletutorial.com)



## Chapter 5

### Basic math

Use `expr <math expression>` to do math.  `expr` evaluates bash expressions.  Bash does integer division, so `expr 5 / 2` is `2`.  Special operators:
```
\*  # you must escape the *
%   # modulus
```

To use decimal numbers, it's suggested to pipe a string into the bench calculator (`bc`) and use `-l` to get decimals.  `bc` does not appear to require an escape in front of `*`.

`echo "5 / 2" | bc -l`

However `-l` has some wonky behavior, because `echo "100 % 9" | bc -l` returns `0.00000000000000000001` while removing the flag returns `1` so I don't know what's up with that.

### Using variables

You can store data in variables.  Use lowercase and snake case to avoid overwriting environment variables with your names.  Do not put spaces around the equal sign.

`chapter_number=5`

Print this by `echo`ing with a `$` in front.

`echo $chapter_number`

Use `let` to modify the value.

`let chapter_number=$chapter_number+1`

Use **command substitution** to run a command and assign the output as a string to a variable.

`math_lines=$(cat math.sh | wc -l)`

Use `$variable_name` inside strings to substitute.

`echo "The math file has $math_lines lines."`

You can pass arguments to a shell script.  `$@` denotes the array of arguments.  `$#` counts the arguments.  `$1`, `$2`, etc. represents each argument in turn.

You can prompt a user for input with the `read` command.  Place `read varname` in a script to save the user input as `varname`.

### Logic

The exit status of the last program run is stored in a variable called `?`.  To see it, use `echo $?`.  A successful program exits with status `0`.

Exit status is important when using logical operators `&&` and `||`.  For programs separated by `&&`, the chain of programs continues executing if the previous (left-hand-side) program exited with `0`.  The chain up to the first non-`0` will execute, with all their attendant consequences.  For programs separated by `||`, the programs to the right are only executed if the programs to the left have non-`0` status.  Chaining these together will result in the first non-`0` program's being run.

You can combine `&&` and `||` chains.  `||` takes precedence.

### Conditional expressions

Conditional expressions are logical statements that evaluate to `true` or `false`.  They are written between `[[ ]]` and use logical flags or logical operators.

#### Logical flags

An example of a logical flag is `4 -gt 3` for "4 greater than 3".  To see the result of a logical expression, try this trick:

`[[ your expression here ]] && echo t || echo f`

These so-called binary logical expressions compare values (`4 -gt 3`).  But you can use `unary` logical expressions to check a single value, such as `-e somefile.ext` to check if a file exists.  In logical expressions variables (`$somevar`) behave like raw values, _e.g._ `[[ $somevar -gt 3 ]]`.

Common logical flags:

| Logical Flag | Meaning | Usage |
|:-------------|:--------|:------|
| -gt | **G**reater **T**han | `[[ $planets -gt 8 ]]` |
| -ge | **G**reater Than or **E**qual To | `[[ $votes -ge 270 ]]` |
| -eq | **Eq**ual | `[[ $fingers -eq 10 ]]` |
| -ne | **N**ot **E**qual | `[[ $pages -ne 0 ]]` |
| -le | **L**ess Than or **E**qual To | `[[ $candles -le 9 ]]` |
| -lt | **L**ess **T**han | `[[ $wives -lt 2 ]]` |
| -e | A File **E**xists | `[[ -e $taxes_2016 ]]` |
| -d | A **D**irectory Exists | `[[ -d $photos ]]` |
| -z | Length of String is **Z**ero | `[[ -z $name ]]` |
| -n | Length of String is **N**on-Zero | `[[ -n $name ]]` |


#### Logical operators

Logical operators perform an action and return a result.  The regex match operator `=~` is a common one which compares a string on the left to a regex on the right.  In the event of a match, the expression evaluates to `true`.

This is false:

`[[ rhythm =~ [aeiou] ]]`

This is true:

```
word=junk
[[ $word =~ j.*k& ]]
```

The NOT operator `!` reverses a `true` or `false`.

Common logical operators:


| Logical Operator | Meaning | Usage |
|:-------------|:--------|:------|
| =~ | Matches Regular Expression | `[[ $consonants =~ [aeiou] ]]` |
| = | String Equal To | `[[ $password = "pegasus" ]]` |
| != | String Not Equal To | `[[ $fruit != "banana" ]]` |
| ! | Not | `[[ ! "apple" =~ ^b ]]` |


### If and Else

Use conditional expressions to control bash programs.

Here's a simple one:

```
if [[ some condition ]]
then
    some action
fi
```

You can add `else` statements too:

```
if [[ some condition ]]
then
    action1
else
    action2
fi
```

If your conditional expression is looking for arguments from the command line, but you don't supply one, your expression will probably evaluate to `false`.  I guess?

You can also use `elif` statements.  These work just like `if` statements.

```
if [[ condition1 ]]
then
    action1
elif [[ condition2 ]]
then
    action2
else
    action3
fi
```

You can, of course, combine conditional expressions and if/else logic.
 
```
if [[ some condition ]] && [[ some other condition ]]
then
   do something
else
    do something else
fi
```

You can nest `if` statements as well.

```
if [[ condition1 ]]
then
    if [[ condition2 ]]
    then
        action1
    elif [[ condition3 ]]
    then
        action2
    else
        action3
    fi
else
    action4
fi
```

### Arrays

Arrays are ordered lists of values, created within `()`, separating elements with spaces.  You can assign these to a variable.  Access the array with "parameter expansion", i.e. `echo ${array_name[*]}`.  You can select elements with `[]` indexing starting from 0.

```
myarray=(item1 item2 item3 item4)
array_item2=${my_array[1]}
echo ${myarray[*]}
```

Directly reassign elements the way you'd think: `myarray[2]=newitem`.  You can index past the end of your array to extend it.

Subset the array with `${myarray[*]:start_index:n_elements}`.

Use `#` to get the array length: `${#myarray[*]}`.

Add an array to the end of an existing array with `+=`, as in `myarray+=(newitem1 newitem2 newitem3)`.


### Braces

"Brace expansion" uses `{ .. }` to create a sequence of letters or numbers, _e.g._ `echo {0..9}` to get numbers 1 through 9.  This works for upper- and lower-case letters as well.  Putting strings on either side of the braces will paste the string to each element, _e.g._ `echo a{1..4}`.  Or concatenate braces for a cross-join of the elements, _e.g._ `echo {1..3}{A..C}`.

To use variables in braces, you must evaluate the expression with `eval`.

`eval echo {$start..$end}`

Concatenate sequences with a comma inside of brackets, _e.g._ `echo {{1..3},{a..c}}` or `echo {A,B,Y,Z}`.


### Loops

#### for-loops

Syntax:

```
for variable in [sequence]
do
    some action with variable
done
```

Valid sequences are brace expansions:

`for i in {1..5}`

lists of strings

`for i in item1 item2 item3`

arrays

`for element in ${myarray[*]}`

and command substitutions

`for item in $(ls)`.


#### while-loops

While-loops use conditional expressions:

```
count=3
while [[ $count -gt 0 ]]
do
    echo "count is equal to $count"
    let count=$count-1
done
```


#### Nesting

For-loops and while-loops can be nested inside each other.

```
for number in {1..3}
do
  for letter in a b
  do
    echo "number is $number, letter is $letter"
  done
done
```

You can also next `if` statements!

```
for number in {1..10}
do
  if [[ $number -lt 3 ]] || [[ $number -gt 8 ]]
  then
    echo $number
  fi
done
```



### Functions

Syntax:

```
function fun_name {
  code
}
```

The usual bash arguments _e.g._ `$1`, `$2`, `$@`, work as inputs to function bodies (definitions).  To bring functions defined in a script into the current session, use `source scriptname.sh`.  Remember, if you need to loop over every input element do something like `for elt in $@`.

Functions are used primarily for computing values and for side effects.  Functions that have side effects include `mv` and `cp`, and such functions don't print values when they succeed.

You can retrieve values returned by functions.  Variables created inside functions become globally available, so you can use them with the usual `$varname` convention.  Note that this is considered to be a side-effect.  It will overwrite variables that might be used at the global shell prompt.  Avoid this with the `local` keyword when defining variables in function bodies.

```
function add_seq {  # adds all numbers of an array
  local sum=0
  for element in #@; do;
    let sum=sum+$element
  done
  echo $sum
}
```

Now use command substitution to capture the output.

```
my_sum=$(add_seq 1 2 3 4)
```


### Writing programs

Ken Thompson: each Unix program should do one thing well.  Limit program size for code readability, debuggability, and composability.  Composability is demonstrated through the `|` operator.  Consider whether your program could be used in a pipeline and organize the code accordingly.

The idea of "quietness" means that a function should not print to the console if it doesn't have to.  Cases for printing are: inform the user of a value (_e.g._ `pwd`), display the result of a computation, or signal an error.

#### Executables

`ls -l` prints permissions information.  We can grant read (`r`), write (`w`), and execute (`x`) permissions.  Permissions are listed in threes, for `owner`, `group`, and `all`.  The `chmod` command changes permissions.

`chmod` takes the following arguments.  First we can specify which set of users we're going to change
permissions for:

|Character  |Meaning |
|:----------|:-------|
|`u` |The owner of the file |
|`g` |The group that the file belongs to |
|`o` |Everyone else  |
|`a` |Everyone above |

We then need to specify whether we're going to add, remove, or set the
permission:

|Character  |Meaning |
|:----------|:-------|
|`+` |Add permission |
|`-` |Remove permission |
|`=` |Set permission  |

Finally we specify what permission we're changing:

|Character  |Meaning |
|:----------|:-------|
|`r` |Read a file |
|`w` |Write to or edit a file |
|`x` |Execute a file  |

Making a file executable means we only have to type the name of the file to run it.

`chmod u+x filename`

Generally speaking one must prepend the file path in order to run a program, even if it's in the same directory such as `./filename`.  But this does not always seem to be the case.  Always put a shebang at the top of executables.

#### Environment variables

To use executable scripts as shell commands, we must put them in the `PATH`, which is an environment variable.  Environment variables are created by bash and store data about the current computing environment.  They are all capitalized.  Some examples: `HOME`, `PWD`, `PATH`.

Changing the `PATH` variable allows us to make a program available as a command.  When the shell initializes it searches the directories in `PATH` for executables and makes the commands available to the shell.  Adding a directory with executables in it to the `PATH` makes them available.

The `PATH` must be modified every new session, so place the modifications in the `.bashrc` (or `.bash_profile`) like so:

`export PATH=/path/to/commands:$PATH`

Alternatively you can add lines in the `.bashrc` to source individual files.



## Ch 6: Git

### Getting started

Undo the most recent commit:

`git reset --soft HEAD~`
This keeps the files staged but reverts the commit.


### Help, logs, and diffs

Get help on a `git` command with `git help [command]` _e.g._ `git help status`.


### Branching

`HEAD` represents the most recent commit on the branch which is currently checked out.


### GitHub

To add a remote, use `git remote add [remote-name] [URL]`.  If it's a new repository, the remote name should be `origin`.  If you've forked a repo, then YOUR copy of the repo will be `origin` and you can add the upstream repo as `upstream`.

For the first push to `origin` from a local repo that has just added `origin` at the command line, use the `-u` flag.  This sets `origin` as the default remote repository.

#### Markdown readme

Markdown is a markup language.  Markup langauges are sets of rules for adding decorative features to text.  HTML, XML, and LaTeX are examples.  GitHub transforms `.md` files into HTML web pages in your repo.  Any folder can have a `README.md` that GitHub will render for you.  GitHub comments accept markdown as well.


## Chapter 7: Nephology

### Moving stuff in the cloud

The `scp` command lets you move files between local machines and cloud machines.

### Talking to servers

A popular command-line program for talking to servers is called `curl`.  The command lets us send requests and information to other servers.  To download with `curl`, we do:

`curl -O http://site.com/file.ext`

Use `curl` to communicate with APIs as well.  Simply make a call to `curl https://api.sitename.come/blah/blah` to receive `stdout` with the API's response.  Note that `curl` sends HTTP requests, which have different categories called verbs.  The default verb sent by `curl` is GET.  These "GET requests" ask servers to send data to their IP address.

Generally you add arguments to an HTTP API request by appending `?arg` to the API's URL, e.g.

`curl http://some.site.com/dir?argument_value`

But usually we have to specify the argument's name, such as

`curl http://some.site.com/dir?argument_name=argument_value`.

Separate arguments with the ampersand:

`curl http://some.site.com/dir?arg1=value1&arg2=value2`


### Automating tasks

A common program to execute other programs on a schedule is `cron`, a program that is called a daemon and is always running in the background (if enabled; use `ps -A | grep "cron"` to see if it is running).  To assign programs to be executed by `cron`, we edit a text file called a `cron` table.  If enabled, use `select-editor` to choose a default text editor.  Then use `crontab -e` (cron table edit) which will open the `cron` table in the default editor.  Add instructions to the `cron` table as follows:

`m h dom mon dow command`

where the abbreviations specify when to run the job, given by

1. Minute (`m`)
2. Hour (`h`)
3. Day of Month (`dom`)
4. Month (`mon`)
5. Day of Week (`dow`)

and the space-separated columns take on valid values

1. Minute: `00 - 59` (A particular minute in an hour)
2. Hour: `00 - 23` (0 is the midnight hour)
3. Day of Month: `01 - 31` (1 is the first day of the month)
4. Month: `01 - 12` (1 is January)
5. Day of Week `0 - 6` (0 is Sunday).

A `*` is a valid value which means "run every [unit]", _e.g._ `*` in the `h` column means "run every hour".  So to print the date to a file every minute of every hour, you would do

`* * * * * date >> ~/date-file.txt`.

Once the `cron` table is saved, the job can begin at the next scheduled interval.   Typically the command for the `cron` job is `bash something.sh`.

Here is a look at recurring `cron` jobs:

```
# m h  dom mon dow   command
00 * * * * bash /path/to/script.sh     # Runs every hour at the start of the hour
00 12 * * * bash /path/to/script.sh    # Runs every day at noon
* 12 * * * bash /path/to/script.sh     # Runs every minute between 12pm and 12:59pm
00 00 05 * * bash /path/to/script.sh   # Runs the 5th day of every month at midnight
00 00 * 07 * bash /path/to/script.sh   # Runs every day in the month of July at midnight
00 00 * * 2 bash /path/to/script.sh    # Runs every Tuesday at midnight
```

You can also use `-` for ranges and `,` for items in a list.  Here are some examples:

```
# m h  dom mon dow   command
00-04 * * * * bash /path/to/script.sh       # Runs every minute for the first five minutes of every hour
00 00 * * 0,6 bash /path/to/script.sh       # Runs at midnight every Saturday and Sunday
00 03 01-15 * * bash /path/to/script.sh     # Runs at 3am for the first fifteen days of every month 
00,30 * * * * bash /path/to/script.sh       # Runs at the start and middle of every hour
00 00,12 * * * bash /path/to/script.sh      # Runs every day at midnight and noon
00 * 01-07 01,06 * bash /path/to/script.sh  # Runs at the start of every hour for the first seven days of the months of January and June
```
